import { StyleSheet } from 'react-native';
import { COLORS } from '../domain/model';

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: COLORS.bg },
  centeredScroll: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 14,
    backgroundColor: COLORS.bg,
  },
  dashboardScroll: {
    padding: 15,
    paddingBottom: 108,
    backgroundColor: COLORS.bgSoft,
    gap: 16,
  },
  formScroll: {
    padding: 15,
    paddingBottom: 120,
    backgroundColor: COLORS.bgSoft,
    gap: 16,
    flexGrow: 1,
  },
  manageTaskScrollContent: {
    padding: 15,
    paddingBottom: 120,
    backgroundColor: COLORS.bgSoft,
    gap: 16,
  },
  manageTaskPage: { backgroundColor: COLORS.bgSoft },
  flexOne: { flex: 1 },
  rowGap: { flexDirection: 'row', gap: 12 },
  halfWidth: { flex: 1 },
  gradientSurface: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    overflow: 'hidden',
  },
  gradientLinear: {
    ...StyleSheet.absoluteFill,
  },
  gradientHighlight: {
    ...StyleSheet.absoluteFill,
  },
  gradientShade: {
    ...StyleSheet.absoluteFill,
  },
  gradientBase: { ...StyleSheet.absoluteFill, backgroundColor: COLORS.indigo },
  gradientGlowPurple: {
    position: 'absolute',
    width: 420,
    height: 420,
    borderRadius: 210,
    left: -120,
    top: -100,
    backgroundColor: '#A855F7',
    opacity: 0.78,
  },
  gradientGlowIndigo: {
    position: 'absolute',
    width: 460,
    height: 460,
    borderRadius: 230,
    left: '16%',
    top: '-2%',
    backgroundColor: '#7C3AED',
    opacity: 0.58,
  },
  gradientGlowBlue: {
    position: 'absolute',
    width: 430,
    height: 430,
    borderRadius: 215,
    right: -120,
    bottom: -80,
    backgroundColor: '#3B82F6',
    opacity: 0.32,
  },
  gradientGlowLavender: {
    position: 'absolute',
    width: 360,
    height: 360,
    borderRadius: 180,
    left: -40,
    bottom: 40,
    backgroundColor: '#A78BFA',
    opacity: 0.26,
  },
  gradientGlowSky: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    right: 30,
    top: 120,
    backgroundColor: '#60A5FA',
    opacity: 0.12,
  },
  gradientOverlayTop: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: '58%',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  gradientOverlayBottom: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    height: '48%',
    backgroundColor: 'rgba(30,41,59,0.10)',
  },
  gradientShine: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    right: -10,
    top: -110,
    backgroundColor: '#FFFFFF',
    opacity: 0.09,
  },
  splashOuter: {
    flex: 1,
    backgroundColor: COLORS.indigo,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  splashPanel: {
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.indigo,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashGradient: {
    ...StyleSheet.absoluteFill,
  },
  splashHighlight: {
    ...StyleSheet.absoluteFill,
  },
  splashShade: {
    ...StyleSheet.absoluteFill,
  },
  splashOrbLeft: {
    position: 'absolute',
    top: 48,
    left: -12,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  splashOrbRight: {
    position: 'absolute',
    right: -44,
    bottom: 36,
    width: 408,
    height: 408,
    borderRadius: 204,
    backgroundColor: 'rgba(167,139,250,0.22)',
  },
  splashOrbCenter: {
    position: 'absolute',
    top: '46%',
    left: '50%',
    marginLeft: -140,
    marginTop: -140,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(96,165,250,0.12)',
  },
  splashVeil: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(79,70,229,0.03)',
  },
  splashContent: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 40,
  },
  splashLogoWrap: {
    width: 146,
    height: 146,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  splashGlowRing: {
    position: 'absolute',
    width: 116,
    height: 116,
    borderRadius: 68,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  splashLogoCore: {
    width: 92,
    height: 92,
    borderRadius: 22,
    backgroundColor: COLORS.card,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#312E81',
    shadowOpacity: 0.28,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  splashLogoIcon: {
    fontSize: 50,
    lineHeight: 44,
    color: COLORS.indigo,
    fontWeight: '800',
  },
  sparkleTop: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#FDE68A',
  },
  sparkleBottom: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#F9A8D4',
  },
  splashTitle: {
    color: '#FFFFFF',
    fontSize: 38,
    fontWeight: '800',
    marginBottom: 10,
  },
  splashSubtitle: {
    color: 'rgba(237,233,254,0.96)',
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 28,
  },
  progressTrack: {
    width: 256,
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.20)',
    overflow: 'hidden',
  },
  progressFillBar: {
    height: '100%',
    borderRadius: 999,
  },
  progressFillBarFallback: {
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  progressLabel: {
    marginTop: 12,
    fontSize: 14,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.82)',
  },
  loadingDots: { flexDirection: 'row', gap: 8, marginTop: 18 },
  loadingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
  },
  loadingDotSoft: { opacity: 0.88 },
  loadingDotBright: { opacity: 0.72 },
  loginWrap: { width: '100%', maxWidth: 760, alignSelf: 'center' },
  loginHeader: { alignItems: 'center', marginBottom: 36 },
  loginLogoWrap: {
    width: 100,
    height: 100,
    marginBottom: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginLogoShell: {
    width: 74,
    height: 74,
    borderRadius: 22,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4338CA',
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  loginLogoGradient: { ...StyleSheet.absoluteFill },
  loginLogoIcon: {
    color: '#FFFFFF',
    fontSize: 36,
    lineHeight: 40,
    fontWeight: '800',
  },
  loginTitle: {
    fontSize: 36,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 12,
  },
  loginSubtitle: { fontSize: 14, color: '#4338CA', fontWeight: '400' },
  authStepText: {
    marginTop: 12,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textMuted,
  },
  loginHelpText: {
    marginTop: 28,
    textAlign: 'center',
    fontSize: 15,
    color: '#4F46E5',
    fontWeight: '500',
  },
  formHelperText: {
    marginTop: 14,
    color: COLORS.success,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  panel: {
    backgroundColor: COLORS.card,
    borderRadius: 22,
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#F3F4F6',

    // softer shadow
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },

    elevation: 0.1,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 12,
  },
  input: {
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 18,
    // paddingVertical: 15,
    color: COLORS.text,
    marginBottom: 28,
    fontSize: 15,
  },
  passwordInputWrap: {
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingLeft: 18,
    paddingRight: 6,
    marginBottom: 28,
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordInput: {
    flex: 1,
    minHeight: 48,
    paddingVertical: 0,
    paddingRight: 8,
    color: COLORS.text,
    fontSize: 15,
  },
  passwordEyeButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginButton: {
    minHeight: 50,
    borderRadius: 16,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#6366F1',
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  loginButtonGradient: { ...StyleSheet.absoluteFill },
  loginButtonText: { color: '#FFFFFF', fontSize: 17, fontWeight: '700' },
  formErrorText: {
    marginBottom: 14,
    color: COLORS.danger,
    fontSize: 14,
    textAlign: 'center',
  },
  inlineFieldError: {
    marginTop: 8,
    color: COLORS.danger,
    fontSize: 13,
    lineHeight: 18,
  },
  inputNoMargin: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: COLORS.text,
  },
  textArea: { minHeight: 110, textAlignVertical: 'top' },
  heroCard: {
    overflow: 'hidden',
    borderRadius: 22,
    padding: 22,
    minHeight: 210,
    backgroundColor: COLORS.indigo,

    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 12,
  },
  heroGradient: { ...StyleSheet.absoluteFill },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 16,
    marginBottom: 22,
  },
  heroEyebrow: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 15,
    marginBottom: 10,
  },
  heroGreeting: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 6,
  },
  heroSubtext: {
    color: '#E0E7FF',
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 240,
  },
  notificationBubble: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationBubbleIcon: { color: '#FFFFFF', fontSize: 20, fontWeight: '700' },
  notificationDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 12,
    height: 12,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDotInner: {
    width: 8,
    height: 8,
    borderRadius: 9,
    backgroundColor: '#FF3347',
  },
  statsGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  statCard: {
    width: '31%',
    borderRadius: 22,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statValue: {
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 6,
    color: '#FFFFFF',
  },
  statLabel: { color: '#E9D5FF', fontSize: 14, fontWeight: '600' },
  sectionCard: {
    backgroundColor: COLORS.card,
    borderRadius: 22,
    paddingVertical: 18,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    //    shadowColor: '#000',
    // shadowOpacity: 0.025,
    // shadowRadius: 2,
    // shadowOffset: { width: 0, height: 1 },
    // elevation: 1,
    gap: 14,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  sectionTitle: { fontSize: 20, fontWeight: '800', color: COLORS.text },
  linkText: { color: COLORS.indigo, fontSize: 14, fontWeight: '700' },
  chartIntro: {
    color: COLORS.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: -6,
  },
  chartHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  chartFilterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#C7D2FE',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  chartFilterIconButton: {
    width: 38,
    height: 38,
    // borderRadius: 19,
    // borderWidth: 1,
    // borderColor: '#C7D2FE',
    // backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartFilterText: {
    color: COLORS.indigo,
    fontSize: 12,
    fontWeight: '800',
  },
  chartHighlightCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 14,
    // paddingVertical: 14,
    justifyContent: 'center',
    // shadowColor: '#6366F1',
    // shadowOpacity: 0.06,
    // shadowRadius: 12,
    // shadowOffset: { width: 0, height: 6 },
    // elevation: 2,
  },
  chartHighlightEyebrow: {
    color: '#7C3AED',
    fontSize: 12,
    letterSpacing: 3,
    marginBottom: 8,
  },
  chartHighlightValue: { color: '#6D28D9', fontSize: 20, fontWeight: '800' },
  chartHighlightMeta: {
    color: COLORS.textMuted,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 6,
  },
chartMetricChipRow: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  gap: 8,
},
  
  dashboardPerformanceSummary: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  dashboardPerformanceMetric: {
    flex: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E0E7FF',
    gap: 6,
  },
  dashboardPerformanceLabel: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  dashboardPerformanceValue: {
    color: COLORS.text,
    fontSize: 22,
    fontWeight: '800',
  },
  legendChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingRight: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendText: { color: COLORS.textMuted, fontSize: 12, fontWeight: '600' },
  chartCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    minHeight: 190,
    paddingTop: 14,
  },
  analyticsStack: { gap: 14 },
  analyticsCardPrimary: {
    // borderRadius: 24,
    // borderWidth: 1,
    // borderColor: '#E0E7FF',
    backgroundColor: '#F8FAFF',
    paddingHorizontal: 16,
    paddingBottom:16,
  },
  analyticsCardSecondary: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E0E7FF',
    backgroundColor: '#FFFFFF',
    padding: 16,
    gap: 12,
  },
  analyticsTitle: { fontSize: 17, fontWeight: '700', color: COLORS.text },
  dashboardNotificationStatusCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 20,
    padding: 16,
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  dashboardNotificationStatusTitle: {
    color: COLORS.text,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  dashboardNotificationStatusText: {
    color: COLORS.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  dashboardNotificationStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#FFFFFF',
  },
  dashboardNotificationStatusBadgeText: {
    color: COLORS.indigo,
    fontSize: 12,
    fontWeight: '800',
  },
  dashboardNotificationToken: {
    color: COLORS.textSoft,
    fontSize: 12,
    fontWeight: '600',
  },
  chartColumn: { alignItems: 'center', gap: 8, flex: 1 },
  chartBarTrack: {
    width: 24,
    height: 128,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  chartBarAssigned: {
    position: 'absolute',
    bottom: 0,
    width: 22,
    borderRadius: 999,
    backgroundColor: '#DDD6FE',
  },
  chartBarCompleted: {
    width: 14,
    borderRadius: 999,
    backgroundColor: COLORS.success,
    bottom: 0,
  },
  chartLabel: { fontSize: 10, color: COLORS.textMuted, fontWeight: '600' },
  chartLabelActive: { color: COLORS.indigo, fontWeight: '800' },
  chartLegendFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 18,
    marginTop: 4,
  },
  distributionWrap: { gap: 14 },
  distributionRow: { gap: 8 },
  distributionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  distributionLabelWrap: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  distributionDot: { width: 10, height: 10, borderRadius: 5 },
  distributionLabel: { color: COLORS.text, fontSize: 14, fontWeight: '600' },
  distributionValue: { color: COLORS.text, fontSize: 16, fontWeight: '800' },
  distributionTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#EEF2FF',
    overflow: 'hidden',
  },
  distributionFill: { height: '100%', borderRadius: 999 },
  overviewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  overviewCard: {
    width: '47%',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    gap: 8,
  },
  overviewCardActive: { backgroundColor: '#EEF6FF', borderColor: '#BFDBFE' },
  overviewCardCreated: { backgroundColor: '#EEF6FF', borderColor: '#BFDBFE' },
  overviewCardPending: { backgroundColor: '#F5F3FF', borderColor: '#DDD6FE' },
  overviewCardReview: { backgroundColor: '#FDF2F8', borderColor: '#FBCFE8' },
  overviewCardCompleted: { backgroundColor: '#EEFDF3', borderColor: '#BBF7D0' },
  overviewEyebrow: {
    fontSize: 12,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  overviewAccentCreated: { color: '#0284C7' },
  overviewAccentPending: { color: '#7C3AED' },
  overviewAccentReview: { color: '#C026D3' },
  overviewAccentCompleted: { color: '#4338CA' },
  overviewValue: { fontSize: 28, fontWeight: '800', color: COLORS.text },
  overviewDescription: {
    color: COLORS.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  managedTable: {
    // borderRadius: 12,
    // borderWidth: 1,
    // borderColor: '#E5E7EB',
    // overflow: 'hidden',
    // backgroundColor: '#FFFFFF',
  },
  managedTableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#F8FAFC',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  managedHeaderCell: {
    flex: 1,
    textAlign: 'left',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1,
    color: COLORS.textMuted,
    textTransform: 'uppercase',
  },
  managedTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F8FAFC',
  },
  managedUserCell: { flex: 2.2, alignItems: 'flex-start' },
  managedUserName: { fontSize: 14, fontWeight: '700', color: COLORS.text },
  managedUserMeta: { marginTop: 3, fontSize: 12, color: COLORS.textMuted },
  managedCountPill: {
    flex: 1,
    marginLeft: 8,
    borderRadius: 16,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
managedCountPending: { backgroundColor: '#F0F9FF' },
managedCountReview: { backgroundColor: '#FFFBEB' },
managedCountDone: { backgroundColor: '#F0FDF4' },
  managedCountText: { color: COLORS.text, fontSize: 16, fontWeight: '800' },
  segmentedRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    alignSelf: 'flex-start',
  },
  segmentButton: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: COLORS.bgSoft,
  },
  segmentButtonActive: { backgroundColor: COLORS.indigo },
  segmentButtonText: {
    color: COLORS.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  segmentButtonTextActive: { color: '#FFFFFF' },
  bottomNav: {
    // position: 'absolute',
    // left: 20,
    // right: 20,
    // bottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 14,
    // borderWidth: 1,
    // borderColor: '#EEF2F7',
    // shadowColor: '#0F172A',
    // shadowOpacity: 0.08,
    // shadowRadius: 16,
    // shadowOffset: { width: 0, height: 10 },
    // elevation: 5,
  },
  bottomNavItem: { flex: 1, alignItems: 'center', gap: 4 },
  bottomNavIconWrap: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavIcon: { color: COLORS.textSoft },
  bottomNavIconActive: { color: COLORS.indigo },
  bottomNavText: { color: COLORS.textSoft, fontSize: 12, fontWeight: '600' },
  bottomNavTextActive: { color: COLORS.indigo, fontWeight: '800' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.bgSoft,
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  headerIconButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIconText: { fontSize: 24, color: '#334155', marginTop: -2 },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.text,
  },
  headerActionButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: COLORS.indigo,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerActionText: {
    color: '#FFFFFF',
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '700',
  },
  headerSpacer: { width: 42 },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    gap: 8,
  },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  choiceChip: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 14,
    backgroundColor: COLORS.bgSoft,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  choiceChipActive: {
    backgroundColor: COLORS.indigo,
    borderColor: COLORS.indigo,
  },
  choiceChipText: { color: COLORS.textMuted, fontSize: 13, fontWeight: '700' },
  choiceChipTextActive: { color: '#FFFFFF' },
  // badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 12,
    includeFontPadding: false,
    textAlignVertical: 'center',
    overflow: 'hidden',
  },
  badgeHigh: {
    backgroundColor: '#FEE2E2',
    color: '#DC2626',
    borderColor: '#FECACA',
  },
  badgeMedium: {
    backgroundColor: '#FEF3C7',
    color: '#B45309',
    borderColor: '#FCD34D',
  },
  badgeLow: {
    backgroundColor: '#DCFCE7',
    color: '#15803D',
    borderColor: '#BBF7D0',
  },
  statusPending: { backgroundColor: '#DBEAFE', color: '#2563EB' },
  statusProgress: { backgroundColor: '#EDE9FE', color: '#7C3AED' },
  statusCompleted: { backgroundColor: '#DCFCE7', color: '#16A34A' },
  statusReview: { backgroundColor: '#FEF3C7', color: '#D97706' },
  statusDanger: { backgroundColor: COLORS.dangerBg, color: COLORS.danger },
  manageStatusBadgeCompact: {
    // paddingVertical: 3,
    // lineHeight: 12,
  },
  taskCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    gap: 14,
  },
  taskCardHeader: { gap: 6 },
  taskCardTitle: { fontSize: 18, fontWeight: '800', color: COLORS.text },
  taskCardDescription: {
    color: COLORS.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  statusOnTimeBorder: {
    backgroundColor: '#DCFCE7',
    color: '#16A34A',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
  },

  statusDelayedBorder: {
    backgroundColor: '#FEE2E2',
    color: '#DC2626',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
  },
  taskTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  taskMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    // paddingHorizontal: 10,
    // paddingVertical: 2,
    borderRadius: 12,
    // backgroundColor: COLORS.bgSoft,
  },
  metaPillIcon: { color: COLORS.textSoft, fontSize: 12 },
  metaPillText: { color: COLORS.textMuted, fontSize: 12, fontWeight: '600' },
  inlineTimerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  inlineTimerIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inlineTimerIconText: {
    color: COLORS.indigo,
    fontSize: 28,
    fontWeight: '700',
  },
  inlineTimerLabel: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  inlineTimerValue: {
    color: COLORS.text,
    fontSize: 20,
    fontWeight: '800',
    marginTop: 2,
  },
  inlineTimerState: { color: COLORS.indigo, fontSize: 12, fontWeight: '700' },
  taskActionRow: { flexDirection: 'row', gap: 12 },
  taskNextCard: {
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#C7D2FE',
    gap: 6,
  },
  taskNextTitle: { color: COLORS.indigo, fontSize: 13, fontWeight: '800' },
  taskNextText: { color: COLORS.text, fontSize: 14, lineHeight: 20 },
  taskNoteCard: {
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 6,
  },
  taskNoteTitle: { color: COLORS.text, fontSize: 13, fontWeight: '800' },
  taskNoteText: { color: COLORS.textMuted, fontSize: 13, lineHeight: 18 },
  taskInputWrap: { width: '100%' },
  taskInlineInput: {
    minHeight: 88,
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
  },
  reviewCommentCard: {
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#F8FAFC',

    // backgroundColor: '#FFEDD5',
    // borderWidth: 1,
    // borderColor: '#FED7AA',
    gap: 6,
  },
  reviewCommentLabel: { color: '#000000', fontSize: 13, fontWeight: '800' },
  reviewCommentText: { color: '#000000', fontSize: 12, lineHeight: 20 },

  doneSummaryCard: {
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#DCFCE7',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    gap: 6,
  },
  doneSummaryLabel: { color: '#15803D', fontSize: 13, fontWeight: '800' },
  doneSummaryText: { color: '#166534', fontSize: 14, lineHeight: 20 },
  myTasksTabScroll: { flexGrow: 0 },
  myTasksTabScrollContent: { paddingHorizontal: 4, alignSelf: 'flex-start' },
  myTasksTabRow: {
    flexDirection: 'row',
    gap: 5,
    alignSelf: 'flex-start',
  },
  myTasksTabButton: {
    minWidth: 90,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  myTasksTabButtonActive: {
    borderColor: '#7C3AED',
    shadowColor: '#7C3AED',
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  myTasksTabGradient: { ...StyleSheet.absoluteFill },
  myTasksTabText: { color: '#475569', fontSize: 15, fontWeight: '700' },
  myTasksTabTextActive: { color: '#FFFFFF' },
  taskListSearchInput: {
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 16,
    color: COLORS.text,
    fontSize: 15,
  },
  taskListMetaText: {
    color: COLORS.textMuted,
    fontSize: 13,
    lineHeight: 18,
    paddingHorizontal: 10,
    alignSelf: 'flex-end',
  },
  paginationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 2,
  },
  paginationButton: {
    minWidth: 96,
    minHeight: 42,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  paginationButtonDisabled: {
    opacity: 0.45,
  },
  paginationButtonText: {
    color: COLORS.indigo,
    fontSize: 14,
    fontWeight: '700',
  },
  paginationText: {
    flex: 1,
    color: COLORS.textMuted,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  manageTabsTight: { marginBottom: 4 },
  manageTaskListTight: { gap: 16 },
  manageTabsWrap: {
    minHeight: 64,
    justifyContent: 'center',
  },
  manageTabsScroll: {
    marginTop: 4,
    marginBottom: 4,
    minHeight: 60,
  },
  manageTabsScrollContent: {
    paddingRight: 8,
    alignItems: 'center',
  },
  manageTabsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  manageTabButton: {
    minWidth: 132,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginRight: 10,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 0,
  },
  manageTabButtonActive: {
    borderColor: '#6366F1',
    shadowColor: '#6366F1',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  manageTabGradient: { ...StyleSheet.absoluteFill },
  manageTabText: { color: '#475569', fontSize: 15, fontWeight: '700' },
  manageTabTextActive: { color: '#FFFFFF' },
  manageTextArea: { minHeight: 160, textAlignVertical: 'top' },
  pickerField: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'center',
  },
  pickerFieldText: {
    color: COLORS.text,
    fontSize: 15,
  },
  pickerFieldPlaceholder: {
    color: COLORS.textSoft,
  },
  alarmPickerWrap: {
    flexDirection: 'row',
    gap: 14,
  },
  alarmColumn: {
    flex: 1,
    gap: 10,
  },
  alarmColumnLabel: {
    color: COLORS.textMuted,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  alarmColumnScroll: {
    maxHeight: 280,
  },
  alarmOptionButton: {
    minHeight: 52,
    marginBottom: 10,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  alarmOptionButtonActive: {
    borderColor: COLORS.indigo,
  },
  alarmOptionGradient: { ...StyleSheet.absoluteFill },
  alarmOptionText: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  alarmOptionTextActive: {
    color: '#FFFFFF',
  },
  manageDoneBadge: {
    backgroundColor: '#DBEAFE',
    color: '#2563EB',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  manageReviewBadge: {
    backgroundColor: '#DBEAFE',
    color: '#2563EB',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  manageSummaryCard: {
    // borderRadius: 18,
    // padding: 14,
    // backgroundColor: '#F8FAFC',
    // borderColor: '#E2E8F0',
    gap: 10,
  },
  manageSummaryTitle: { color: COLORS.text, fontSize: 11, fontWeight: '800' },
  manageSummaryText: { color: COLORS.textMuted, fontSize: 14, lineHeight: 20 },
  selectField: {
    minHeight: 58,
    borderRadius: 22,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectFieldText: { color: COLORS.text, fontSize: 15 },
  selectFieldArrow: { color: COLORS.text, fontSize: 22, marginTop: -4 },
  assignChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  assignDropdownList: {
    maxHeight: 360,
  },
  assignDropdownWrap: {
    gap: 10,
  },

  assignDropdownItem: {
    minHeight: 70,
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  assignDropdownItemActive: {
    borderColor: COLORS.indigo,
  },
  assignDropdownGradient: { ...StyleSheet.absoluteFill },
  assignDropdownName: {
    color: COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  assignDropdownNameActive: {
    color: '#FFFFFF',
  },
  assignDropdownRole: {
    color: COLORS.textMuted,
    fontSize: 13,
    marginTop: 3,
  },
  assignDropdownRoleActive: {
    color: '#EDE9FE',
  },
  bottomSpacer: { height: 92 },
  detailsTitle: { fontSize: 24, fontWeight: '800', color: COLORS.text },
  detailsDesc: { color: COLORS.textMuted, fontSize: 15, lineHeight: 22 },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 16,
  },
  infoLabel: { color: COLORS.textMuted, fontSize: 14, fontWeight: '600' },
  infoValue: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'right',
    flexShrink: 1,
  },
  profileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingVertical: 28,
    paddingHorizontal: 22,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    shadowColor: '#000',
    shadowOpacity: 0.025,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 0.5,
  },
  profileAvatar: {
    width: 102,
    height: 102,
    borderRadius: 51,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  profileAvatarGradient: { ...StyleSheet.absoluteFill },
  profileAvatarText: { color: '#FFFFFF', fontSize: 30, fontWeight: '800' },
  profileName: {
    color: COLORS.text,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 8,
  },
  profileEmail: { color: '#475569', fontSize: 14, marginBottom: 6 },
  profilePhone: { color: '#64748B', fontSize: 14 },
  profileStatsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 22,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    // shadowColor: '#000',
    // shadowOpacity: 0.025,
    // shadowRadius: 2,
    // shadowOffset: { width: 0, height: 1 },
    // elevation: 1,
    gap: 18,
  },
  profileSectionTitle: { color: COLORS.text, fontSize: 18, fontWeight: '800' },
  profileStatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  profileStatLabel: { color: '#475569', fontSize: 14 },
  profileStatValue: { fontSize: 16, fontWeight: '800' },
  profileActionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    minHeight: 65,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    // shadowColor: '#000',
    // shadowOpacity: 0.015,
    // shadowRadius: 1,
    // shadowOffset: { width: 0, height: 0.5 },
    // elevation: 0.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileActionLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  profileActionIcon: { color: '#475569', fontSize: 18, fontWeight: '700' },
  profileActionText: { color: COLORS.text, fontSize: 15, fontWeight: '700' },
  profileActionArrow: { color: '#94A3B8', fontSize: 26, marginTop: -2 },
  manageUsersTabsScroll: {
    paddingRight: 8,
  },
  manageUsersTabsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  manageUsersTabButton: {
    minWidth: 120,
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  manageUsersTabButtonActive: {
    borderColor: COLORS.indigo,
  },
  manageUsersTabGradient: { ...StyleSheet.absoluteFill },
  manageUsersTabText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '700',
  },
  manageUsersTabTextActive: {
    color: '#FFFFFF',
  },
  manageUsersList: {
    gap: 12,
  },
  userRowCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  userRowMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  userAvatarMini: {
    width: 48,
    height: 48,
    borderRadius: 24,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatarMiniGradient: { ...StyleSheet.absoluteFill },
  userAvatarMiniText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  userRowName: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '800',
  },
  userRowMeta: {
    color: COLORS.textMuted,
    fontSize: 13,
    marginTop: 3,
  },
  userRowActions: {
    flexDirection: 'row',
    gap: 10,
  },
  userActionButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userActionEdit: {
    color: COLORS.indigo,
    fontSize: 18,
    fontWeight: '800',
  },
  userActionDelete: {
    color: '#DC2626',
    fontSize: 18,
    fontWeight: '800',
  },
  userActionDisabled: {
    color: '#CBD5E1',
  },
  userRolePlaceholder: {
    color: COLORS.textSoft,
  },
  assignmentSummaryList: {
    gap: 14,
  },
  assignmentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    gap: 16,
  },
  assignmentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  assignmentName: {
    color: COLORS.text,
    fontSize: 17,
    fontWeight: '800',
  },
  assignmentRole: {
    color: COLORS.textMuted,
    fontSize: 13,
    marginTop: 4,
  },
  assignmentTotal: {
    color: COLORS.indigo,
    fontSize: 13,
    fontWeight: '800',
  },
  assignmentStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  assignmentStatPill: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
  },
  assignmentStatLabel: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  assignmentStatValue: {
    color: COLORS.text,
    fontSize: 20,
    fontWeight: '800',
  },
  assignmentCardFooter: {
    flex: 1,
    minHeight: 76,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  assignmentOpenText: {
    flex: 1,
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  assignmentOpenArrow: {
    color: COLORS.indigo,
    fontSize: 26,
    marginTop: -2,
  },
  assignmentTaskList: {
    gap: 10,
  },
  assignmentTaskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  assignmentTaskTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },
  assignmentTaskMeta: {
    color: COLORS.textMuted,
    fontSize: 12,
    marginTop: 4,
  },
  assignmentTaskStatus: {
    color: COLORS.indigo,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  assignmentEmptyText: {
    color: COLORS.textMuted,
    fontSize: 14,
  },
  userRoleModalCard: {
    width: '88%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 22,
    gap: 16,
  },
  userRoleOptionList: {
    gap: 10,
  },
  userRoleOption: {
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  userRoleOptionActive: {
    borderColor: COLORS.indigo,
  },
  userRoleOptionGradient: {
    ...StyleSheet.absoluteFill,
  },
  userRoleOptionText: {
    color: COLORS.text,
    fontSize: 15,
    fontWeight: '700',
  },
  userRoleOptionTextActive: {
    color: '#FFFFFF',
  },
  userDetailsOverviewCardActive: {
    borderColor: '#4F46E5',
    borderTopColor: '#818CF8',
    borderBottomColor: '#3730A3',
    borderWidth: 1.5,
    shadowColor: '#4F46E5',
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  userDetailsOverviewGradient: {
    ...StyleSheet.absoluteFill,
  },
  userDetailsDoneText: {
    color: '#16A34A',
  },
  userDetailsDownloadRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 8,
  },
  userDetailsDownloadButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  userDetailsDownloadText: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  userDetailsTaskList: {
    gap: 12,
  },
  userDetailsTaskCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 8,
  },
  userDetailsTaskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  userDetailsTaskTitle: {
    flex: 1,
    color: COLORS.text,
    fontSize: 15,
    fontWeight: '800',
  },
  userDetailsTaskStatus: {
    color: COLORS.indigo,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  userDetailsTaskDescription: {
    color: COLORS.textMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  userDetailsTaskMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  userDetailsTaskMeta: {
    color: COLORS.textMuted,
    fontSize: 12,
  },
  logoutCard: {
    minHeight: 60,
    borderRadius: 16,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FEE2E2',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.015,
    shadowRadius: 1.5,
    shadowOffset: { width: 0, height: 0.5 },
    elevation: 0.5,
  },
  logoutIcon: { color: '#FF0000', fontSize: 22, fontWeight: '700' },
  logoutText: { color: '#FF0000', fontSize: 16, fontWeight: '800' },
  feedbackCard: {
    backgroundColor: '#FFF7ED',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#FED7AA',
    gap: 8,
  },
  feedbackTitle: { color: '#C2410C', fontSize: 15, fontWeight: '800' },
  feedbackText: { color: '#9A3412', fontSize: 14, lineHeight: 20 },
  alertCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    backgroundColor: '#EEF2FF',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  alertIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertIcon: { color: COLORS.indigo, fontSize: 20, fontWeight: '800' },
  alertTitle: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  alertText: { color: COLORS.textMuted, fontSize: 14, lineHeight: 20 },
  assignedPerson: { color: COLORS.text, fontSize: 20, fontWeight: '800' },
  assignedRole: { color: COLORS.textMuted, fontSize: 14 },
  heroTimerCard: {
    overflow: 'hidden',
    borderRadius: 28,
    padding: 22,
    alignItems: 'center',
    gap: 8,
  },
  heroTimerGradient: { ...StyleSheet.absoluteFill },
  timerHeroLabel: {
    color: '#E0E7FF',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  timerHeroValue: { color: '#FFFFFF', fontSize: 36, fontWeight: '800' },
  timerHeroState: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  reviewAlert: { backgroundColor: '#ECFDF5', borderColor: '#A7F3D0' },
  reviewAlertIconWrap: { backgroundColor: '#FFFFFF' },
  reviewAlertIcon: { color: COLORS.success },
  dangerAlert: { backgroundColor: COLORS.dangerBg, borderColor: '#FCA5A5' },
  dangerAlertIconWrap: { backgroundColor: '#FFFFFF' },
  dangerAlertIcon: { color: COLORS.danger },
  noteText: { color: COLORS.text, fontSize: 15, lineHeight: 22 },
  notificationCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    position: 'relative',
  },
  notificationCardUnread: {
    backgroundColor: '#EEF2FF',
    borderColor: '#C7D2FE',
  },
  notificationIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationIcon: { color: COLORS.deepBlue, fontSize: 18, fontWeight: '800' },
  notificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 4,
  },
  notificationTitle: {
    flex: 1,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '800',
  },
  notificationTime: { color: COLORS.textSoft, fontSize: 12, fontWeight: '600' },
  notificationMessage: {
    color: COLORS.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  unreadDot: {
    position: 'absolute',
    top: 16,
    right: 10,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.indigo,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 18,
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: COLORS.bgSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyIcon: { color: COLORS.textSoft, fontSize: 24, fontWeight: '700' },
  emptyTitle: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  emptySubtitle: {
    color: COLORS.textMuted,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
  buttonBase: {
    minHeight: 50,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    position: 'relative',
  },
  buttonHalf: { flex: 1 },
  buttonGradient: { ...StyleSheet.absoluteFill },
  buttonPrimary: {
    borderColor: '#6366F1',
    backgroundColor: COLORS.indigo,
    shadowColor: '#6366F1',
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  buttonSecondary: { borderColor: '#D1D5DB', backgroundColor: '#FFFFFF' },
  buttonSuccess: { borderColor: '#86EFAC', backgroundColor: COLORS.success },
  buttonWarning: { borderColor: '#6366F1', backgroundColor: '#FFFFFF' },
  buttonGhost: {
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  buttonDanger: { borderColor: '#FCA5A5', backgroundColor: COLORS.danger },
  buttonText: { fontSize: 17, fontWeight: '800' },
  buttonTextLight: { color: '#FFFFFF' },
  buttonTextSecondary: { color: COLORS.text },
  buttonTextWarning: { color: COLORS.indigo },
  buttonTextGhost: { color: '#FFFFFF' },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15,23,42,0.35)',
  },
  modalOverlayCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.28)',
    padding: 24,
  },
  bottomSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 22,
    gap: 14,
  },
  pickerModalCard: {
    width: '100%',
    maxWidth: 380,
    maxHeight: '95%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    gap: 16,
  },
  inlineMoreTimeOverlay: {
    position: 'absolute',
    left: 16,
    right: 16,
    top: 96,
    zIndex: 10,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  calendarNavButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarNavButtonText: {
    color: COLORS.text,
    fontSize: 22,
    fontWeight: '700',
    marginTop: -2,
  },
  calendarMonthText: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: '800',
  },
  calendarWeekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarWeekdayText: {
    width: '14.28%',
    textAlign: 'center',
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  calendarDayPlaceholder: {
    width: '12%',
    aspectRatio: 1,
  },
  calendarDayButton: {
    width: '12%',
    minWidth: 38,
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  calendarDayButtonActive: {
    borderColor: COLORS.indigo,
  },
  calendarDayButtonDisabled: {
    backgroundColor: '#F8FAFC',
    borderColor: '#EEF2F7',
    opacity: 0.45,
  },
  calendarDayGradient: { ...StyleSheet.absoluteFill },
  calendarDayText: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },
  calendarDayTextActive: {
    color: '#FFFFFF',
  },
  calendarDayTextDisabled: {
    color: COLORS.textSoft,
  },
  timePickerList: {
    maxHeight: 360,
  },
  timePickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  timeOptionButton: {
    minWidth: '30%',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  timeOptionButtonActive: {
    borderColor: COLORS.indigo,
  },
  timeOptionGradient: { ...StyleSheet.absoluteFill },
  timeOptionText: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },
  timeOptionTextActive: {
    color: '#FFFFFF',
  },
  modalTitle: { color: COLORS.text, fontSize: 18, fontWeight: '800' },
  modalText: { color: COLORS.textMuted, fontSize: 12 },
  modalButton: {
    marginTop: 12,
    alignSelf: 'flex-end',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#A855F7',
  },

  modalButtonText: {
    color: '#fff',
    fontWeight: '600',
  },

  modalCard: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 20,
    gap: 12,
  },

  successCard: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 24,
    alignItems: 'center',
    gap: 8,
  },
  successIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  successIcon: { color: COLORS.success, fontSize: 28, fontWeight: '800' },
  successTitle: { color: COLORS.text, fontSize: 22, fontWeight: '800' },
  successText: {
    color: COLORS.textMuted,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
  durationTabContainer: {
    flexDirection: 'row',
    gap: 10,
    flex: 1,
  },

  durationTab: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    position: 'relative',
  },

  durationTabActive: {
    borderColor: 'transparent',
  },

  durationTabGradient: {
    ...StyleSheet.absoluteFill,
  },

  durationTabText: {
    color: '#94A3B8',
    fontWeight: '600',
    fontSize: 15,
  },

  durationTabTextActive: {
    color: '#fff',
  },
});
